// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

import cloudflare from '@astrojs/cloudflare';

const PAGEFIND_STUB = '\0pagefind-stub';

/** Returns empty results in dev — real index is generated by `npx pagefind --site dist` */
function pagefindDevStub() {
  return {
    name: 'pagefind-dev-stub',
    apply: /** @type {'serve'} */ ('serve'),
    resolveId(/** @type {string} */ id) {
      if (id === '/pagefind/pagefind.js') return PAGEFIND_STUB;
    },
    load(/** @type {string} */ id) {
      if (id === PAGEFIND_STUB) {
        return 'export async function init() {} export async function search() { return { results: [] }; }';
      }
    },
  };
}

export default defineConfig({
  vite: {
    plugins: [tailwindcss(), pagefindDevStub()],
  },

  adapter: cloudflare()
});